services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  users-service:
    ports:
      - "4001:4001"
    environment:
      AUTH_RATE_LIMIT_MAX: "500"
      PASSWORD_RESET_RATE_LIMIT_MAX: "500"
      GENERAL_RATE_LIMIT_MAX: "5000"

  gigs-service:
    ports:
      - "4002:4002"
    environment:
      GENERAL_RATE_LIMIT_MAX: "5000"

  orders-service:
    ports:
      - "4003:4003"
    environment:
      GENERAL_RATE_LIMIT_MAX: "5000"

  requests-service:
    ports:
      - "4004:4004"
    environment:
      GENERAL_RATE_LIMIT_MAX: "5000"
