services:
  users-service:
    ports:
      - "4001:4001"

  gigs-service:
    ports:
      - "4002:4002"

  orders-service:
    ports:
      - "4003:4003"

  requests-service:
    ports:
      - "4004:4004"

  chat-service:
    ports:
      - "4005:4005"
