apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: daddy-services
  labels:
    app: daddy
spec:
  selector:
    matchLabels:
      monitoring: daddy
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
