apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daddy-prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: daddy-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/rh_ee_rmalka/daddy:prod
  - target:
      kind: Secret
      name: daddy-app-secret
    patch: |
      - op: replace
        path: /stringData/AUTH_URL
        value: https://daddy-app-daddy-prod.apps.cluster-cpgwh.cpgwh.sandbox765.opentlc.com
  - target:
      kind: Secret
      name: postgres-secret
    patch: |
      - op: replace
        path: /stringData/POSTGRES_PASSWORD
        value: CHANGE_ME_PROD_PASSWORD
      - op: replace
        path: /stringData/DATABASE_URL
        value: postgresql://daddy:CHANGE_ME_PROD_PASSWORD@postgres:5432/daddy
  - target:
      kind: PersistentVolumeClaim
      name: postgres-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi

labels:
  - pairs:
      environment: prod
