apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daddy-dev

resources:
  - ../../base

components:
  - ../../components/seed-job

patches:
  - target:
      kind: Deployment
      name: daddy-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Secret
      name: daddy-app-secret
    patch: |
      - op: replace
        path: /stringData/AUTH_URL
        value: https://daddy-app-daddy-dev.apps.cluster-x8bxx.x8bxx.sandbox2963.opentlc.com
      - op: replace
        path: /stringData/NEXT_PUBLIC_BASE_URL
        value: https://daddy-app-daddy-dev.apps.cluster-x8bxx.x8bxx.sandbox2963.opentlc.com

labels:
  - pairs:
      environment: dev
