apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-deployment.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-provider.yaml
  - dashboard-system.yaml
  - dashboard-business.yaml
  - dashboard-service.yaml
